### ISSUE TITLE
a message

### ISSUE THREAD

**Issue by ArgentArc** [iwakkrg/iwakkrg.github.io#2]
hey iwak
the thing is i do have an version which is just some fork of yours
would say can i join the club of that type of thing please?
thanks.

-argent arc

**Comment by iwakkrg** [comment]
Sure I guess? I'm not the first one to make this kind of thing anyways

**Comment by ArgentArc** [comment]
i do have an account that was here in 2018 discord either way thats my main account Azatsky#7479
